### PR TITLE
Make snack-cli green again !

### PR DESCRIPTION
**Pull request by williamdes**
- Update dependencies
- Various fixes

### CODE REVIEW

**Comment by williamdes** [comment]
@subchen Can you review this PR ?
Maybe activate Travis CI ?
I can not set the PR as not in progress because no CI is set up ..

**Comment by subchen** [comment]
thanks for your pull request. As you know, the npm package is working on legacy node engine, so I need upgrade major version to 2.0, and release to npmjs.org later.

**Comment by williamdes** [comment]
@subchen Thank you for merging the PR, will make another one since I need this excellent package for some of my projects and github is spamming me that you have a vulnerable/outdated dependency :)
I think we can agree that we need to do :
- Fix CI
- Install coveralls extension to github? 
- Publish new version

Have a nice day, 
William

**Comment by subchen** [comment]
👍 2.0.0 released, 
https://www.npmjs.com/package/snack-cli

**Pull request merged**
