### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by williamdes**
Enhancements

### CODE REVIEW

**Comment by subchen** [comment]
travic-io is failed, will check it later.

```
git.checkout
0.53s$ git clone --depth=50 https://github.com/subchen/snack-cli.git subchen/snack-cli
Cloning into 'subchen/snack-cli'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 71 (delta 0), reused 1 (delta 0), pack-reused 70
Unpacking objects: 100% (71/71), done.
$ cd subchen/snack-cli
0.40s$ git fetch origin +refs/pull/2/merge:
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 17 (delta 8), reused 16 (delta 8), pack-reused 0
Unpacking objects: 100% (17/17), done.
From https://github.com/subchen/snack-cli
 * branch            refs/pull/2/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
nvm.install
2.79s$ nvm install 6
Downloading and installing node v6.17.0...
Downloading https://nodejs.org/dist/v6.17.0/node-v6.17.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v6.17.0 (npm v3.10.10)
$ node --version
v6.17.0
$ npm --version
3.10.10
$ nvm --version
0.34.0
install.npm
33.57s$ npm install 
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN prefer global coffeescript@1.10.0 should be installed with -g
npm WARN prefer global jsonlint@1.6.3 should be installed with -g
snack-cli@1.1.0 /home/travis/build/subchen/snack-cli
├─┬ coveralls@3.0.3 
│ ├── growl@1.10.5 
│ ├─┬ js-yaml@3.12.2 
│ │ ├── argparse@1.0.10 
│ │ └── esprima@4.0.1 
│ ├── lcov-parse@0.0.10 
│ ├── log-driver@1.2.7 
│ ├── minimist@1.2.0 
│ └─┬ request@2.88.0 
│   ├── aws-sign2@0.7.0 
│   ├── aws4@1.8.0 
│   ├── caseless@0.12.0 
│   ├─┬ combined-stream@1.0.7 
│   │ └── delayed-stream@1.0.0 
│   ├── extend@3.0.2 
│   ├── forever-agent@0.6.1 
│   ├─┬ form-data@2.3.3 
│   │ └── asynckit@0.4.0 
│   ├─┬ har-validator@5.1.3 
│   │ ├─┬ ajv@6.10.0 
│   │ │ ├── fast-deep-equal@2.0.1 
│   │ │ ├── fast-json-stable-stringify@2.0.0 
│   │ │ ├── json-schema-traverse@0.4.1 
│   │ │ └─┬ uri-js@4.2.2 
│   │ │   └── punycode@2.1.1 
│   │ └── har-schema@2.0.0 
│   ├─┬ http-signature@1.2.0 
│   │ ├── assert-plus@1.0.0 
���   │ ├─┬ jsprim@1.4.1 
│   │ │ ├── extsprintf@1.3.0 
│   │ │ ├── json-schema@0.2.3 
│   │ │ └── verror@1.10.0 
│   │ └─┬ sshpk@1.16.1 
│   │   ├── asn1@0.2.4 
│   │   ├── bcrypt-pbkdf@1.0.2 
│   │   ├── dashdash@1.14.1 
│   │   ├── ecc-jsbn@0.1.2 
│   │   ├── getpass@0.1.7 
│   │   ├── jsbn@0.1.1 
│   │   └── tweetnacl@0.14.5 
│   ├── is-typedarray@1.0.0 
│   ├── isstream@0.1.2 
│   ├── json-stringify-safe@5.0.1 
│   ├─┬ mime-types@2.1.22 
│   │ └── mime-db@1.38.0 
│   ├── oauth-sign@0.9.0 
│   ├── performance-now@2.1.0 
│   ├── qs@6.5.2 
│   ├── safe-buffer@5.1.2 
│   ├─┬ tough-cookie@2.4.3 
│   │ ├── psl@1.1.31 
│   │ └── punycode@1.4.1 
│   ├── tunnel-agent@0.6.0 
│   └── uuid@3.3.2 
├─┬ grunt@1.0.3 
│ ├── coffeescript@1.10.0 
│ ├─┬ dateformat@1.0.12 
│ │ ├���─ get-stdin@4.0.1 
│ │ └─┬ meow@3.7.0 
│ │   ├─┬ camelcase-keys@2.1.0 
│ │   │ └── camelcase@2.1.1 
│ │   ├─┬ loud-rejection@1.6.0 
│ │   │ ├─┬ currently-unhandled@0.4.1 
│ │   │ │ └── array-find-index@1.0.2 
│ │   │ └── signal-exit@3.0.2 
│ │   ├── map-obj@1.0.1 
│ │   ├─┬ normalize-package-data@2.5.0 
│ │   │ ├── hosted-git-info@2.7.1 
│ │   │ └─┬ validate-npm-package-license@3.0.4 
│ │   │   ├─┬ spdx-correct@3.1.0 
│ │   │   │ └── spdx-license-ids@3.0.3 
│ │   │   └─┬ spdx-expression-parse@3.0.0 
│ │   │     └── spdx-exceptions@2.2.0 
│ │   ├── object-assign@4.1.1 
│ │   ├─┬ read-pkg-up@1.0.1 
│ │   │ ├─┬ find-up@1.1.2 
│ │   │ │ ├── path-exists@2.1.0 
│ │   │ │ └─┬ pinkie-promise@2.0.1 
│ │   │ │   └── pinkie@2.0.4 
│ │   │ └─┬ read-pkg@1.1.0 
│ │   │   ├─┬ load-json-file@1.1.0 
│ │   │   │ ├── graceful-fs@4.1.15 
│ │   │   │ ├─┬ parse-json@2.2.0 
│ │   │   │ │ └─┬ error-ex@1.3.2 
│ │   │   │ │   └── is-arrayish@0.2.1 
│ │   │   │ └── pify@2.3.0 
│ │   │   └── path-type@1.1.0 
│ │   ├─┬ redent@1.0.0 
│ │   │ ├─┬ indent-string@2.1.0 
│ │   │ │ └─┬ repeating@2.0.1 
│ │   │ │   └── is-finite@1.0.2 
│ │   │ └── strip-indent@1.0.1 
│ │   └── trim-newlines@1.0.0 
│ ├── eventemitter2@0.4.14 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.3.0 
│ │ └── glob@5.0.15 
│ ├─┬ glob@7.0.6 
│ │ ├── fs.realpath@1.0.0 
│ │ ├── inflight@1.0.6 
│ │ └── inherits@2.0.3 
│ ├─┬ grunt-cli@1.2.0 
│ │ └── resolve@1.1.7 
│ ├── grunt-known-options@1.1.1 
│ ├─┬ grunt-legacy-log@2.0.0 
│ │ ├── colors@1.1.2 
│ │ └── grunt-legacy-log-utils@2.0.1 
│ ├─┬ grunt-legacy-util@1.1.1 
│ │ └── getobject@0.1.0 
│ ├─┬ iconv-lite@0.4.24[49m 
│ │ └── safer-buffer@2.1.2 
│ ├─┬ js-yaml@3.5.5 
│ │ └── esprima@2.7.3 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.11 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ ├─┬ nopt@3.0.6 
│ │ └── abbrev@1.1.1 
│ ├── path-is-absolute@1.0.1 
│ └─┬ rimraf@2.6.3 
│   └── glob@7.1.3 
├─┬ grunt-cli@1.3.2 
│ ├── interpret@1.1.0 
│ ├─┬ liftoff@2.5.0 
│ │ ├── findup-sync@2.0.0 
│ │ ├─┬ fined@1.1.1 
│ │ │ ├── expand-tilde@2.0.2 
│ │ │ ├─┬ object.defaults@1.1.0 
│ │ │ │ ├── array-each@1.0.1 
│ │ │ │ └── array-slice@1.1.0 
│ │ │ ├── object.pick@1.3.0 
│ │ │ └─┬ parse-filepath@1.0.2 
│ │ │   ├─┬ is-absolute@1.0.0 
│ │ │   │ └─┬ is-relative@1.0.0 
│ │ │   │   └─┬ is-unc-path@1.0.0 
│ │ │   │     └── munc-path-regex@0.1.2 
│ │ │   ├── map-cache@0.2.2 
│ │ │   └─┬ path-root@0.1.1 
│ │ │     └── path-root-regex@0.1.2 
│ │ ├── flagged-respawn@1.0.1 
│ │ ├─┬ is-plain-object@2.0.4 
│ │ │ └── isobject@3.0.1 
│ │ ├─┬ object.map@1.0.1 
│ │ │ ├─┬ for-own@1.0.0 
│ │ │ │ └── for-in@1.0.2 
│ │ │ └── make-iterator@1.0.1 
│ │ ├── rechoir@0.6.2 
│ │ └─┬ resolve@1.10.0 
│ │   └── path-parse@1.0.6 
│ ├─┬ nopt@4.0.1 
│ │ └─┬ osenv@0.1.5 
│ │   ├── os-homedir@1.0.2 
│ │   └── os-tmpdir@1.0.2 
│ └─┬ v8flags@3.1.2 
│   └─┬ homedir-polyfill@1.0.3 
│     └── parse-passwd@1.0.0 
├─┬ grunt-contrib-jshint@2.0.0 
│ ├─┬ chalk@2.4.2 
│ │ ├─┬ ansi-styles@3.2.1 
│ │ │ └─┬ color-convert@1.9.3 
│ │ │   └── color-name@1.1.3 
│ │ └── supports-color@5.5.0 
│ ├── hooker@0.2.3 
│ └── jshint@2.9.7 
├─┬ grunt-jsbeautifier@0.2.13 
│ ├── async@2.6.2 
│ ├─┬ js-beautify@1.9.0 
│ │ ├─┬ config-chain@1.1.12 
│ │ │ └── proto-list@1.2.4 
│ │ ├─┬ editorconfig@0.15.3 
│ │ │ ├── commander@2.19.0 
│ │ │ ├─┬ lru-cache@4.1.5 
│ │ │ │ ├── pseudomap@1.0.2 
│ │ │ │ └── yallist@2.1.2 
│ │ │ └── sigmund@1.0.1 
│ │ ├── glob@7.1.3 
│ │ └── nopt@4.0.1 
│ ├── lodash@4.17.11 
│ ├─┬ rc@1.2.8 
│ │ ├── deep-extend@0.6.0 
│ │ ├── ini@1.3.5 
│ │ └── strip-json-comments@2.0.1 
│ ├── semver@5.6.0 
│ └─┬ underscore.string@3.3.5 
│   ├── sprintf-js@1.0.3 
│   └── util-deprecate@1.0.2 
├─┬ grunt-jscs@3.0.1 
│ ├─┬ jscs@3.0.7 
│ │ ├─┬ chalk@1.1.3 
│ │ │ ├── ansi-styles@2.2.1 
│ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ └── ansi-regex@2.1.1 
│ │ │ ├── strip-ansi@3.0.1 
│ │ ��� └── supports-color@2.0.0 
│ │ ├─┬ cli-table@0.3.1 
│ │ │ └── colors@1.0.3 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├─┬ cst@0.4.10 
│ │ │ ├─┬ babel-runtime@6.26.0 
│ │ │ │ ├── core-js@2.6.5 
│ │ │ │ └── regenerator-runtime@0.11.1 
│ │ │ ├── babylon@6.18.0 
│ │ │ └─┬ source-map-support@0.4.18 
│ │ │   └── source-map@0.5.7 
│ │ ├── estraverse@4.2.0 
│ │ ├── glob@5.0.15 
│ │ ├─┬ js-yaml@3.4.6 
│ │ │ ├── esprima@2.7.3 
│ │ │ └── inherit@2.2.7 
│ │ ├─┬ jscs-jsdoc@2.0.0 
│ │ │ ├─┬ comment-parser@0.3.2 
│ │ │ │ └─┬ readable-stream@2.3.6 
│ │ │ │   ├── isarray@1.0.0 
│ │ │ │   ├── process-nextick-args@2.0.0 
│ │ │ │   └── string_decoder@1.1.1 
│ │ │ └─┬ jsdoctypeparser@1.2.0 
│ │ │   └── lodash@3.10.1 
│ │ ├── jscs-preset-wikimedia@1.0.1 
│ │ ├─┬ jsonlint@1.6.3 
│ │ │ ├── JSV@4.0.2 
│ │ │ └─┬ nomnom@1.8.1 
│ │ │   ├─┬ chalk@0.4.0 
│ │ │   │ ├── ansi-styles@1.0.0 
│ │ │   │ ├── has-color@0.1.7 
│ │ │   │ └── strip-ansi@0.1.1 
│ │ │   └── underscore@1.6.0 
│ │ ├── lodash@3.10.1 
│ │ ├── natural-compare@1.2.2 
│ │ ├── pathval@0.1.1 
│ │ ├─┬ prompt@0.2.14 
│ │ │ ├── pkginfo@0.4.1 
│ │ │ ├─┬ read@1.0.7 
│ │ │ │ └── mute-stream@0.0.8 
│ │ │ ├── revalidator@0.1.8 
│ │ │ ├─┬ utile@0.2.1 
│ │ │ │ ├── async@0.2.10 
│ │ │ │ ├── deep-equal@1.0.1 
│ │ │ │ ├── i@0.3.6 
│ │ │ │ └── ncp@0.4.2 
│ │ │ └─┬ winston@0.8.3 
│ │ │   ├── async@0.2.10 
│ │ │   ├── colors@0.6.2 
│ │ │   ├── cycle@1.0.3 
│ │ │   ├── eyes@0.1.8 
│ │ │   ├── pkginfo@0.3.1 
│ │ │   └── stack-trace@0.0.10 
│ │ ├── 3mreserved-words@0.1.2 
│ │ ├─┬ strip-bom@2.0.0 
│ │ │ └── is-utf8@0.2.1 
│ │ ├── to-double-quotes@2.0.0 
│ │ ├── to-single-quotes@2.0.1 
│ │ ├─┬ vow-fs@0.3.6 
│ │ │ ├── uuid@2.0.3 
│ │ │ └── vow-queue@0.4.3 
│ │ └─┬ xmlbuilder@3.1.0 
│ │   └── lodash@3.10.1 
│ ├── lodash@4.6.1 
│ └── vow@0.4.19 
├── grunt-trimtrailingspaces@4.0.0 
├─┬ istanbul@0.4.5 
│ ├── abbrev@1.0.9 
│ ├── async@1.5.2 
│ ├─┬ escodegen@1.8.1 
│ │ ├── esprima@2.7.3 
│ │ ├── estraverse@1.9.3 
│ │ ├── esutils@2.0.2 
│ │ ├─┬ optionator@0.8.2 
│ │ │ ├── deep-is@0.1.3 
│ │ │ ├── fast-levenshtein@2.0.6 
│ │ │ ├── levn@0.3.0 
│ │ │ ├── prelude-ls@1.1.2 
│ │ │ └── type-check@0.3.2 
│ │ └─┬ source-map@0.2.0 
│ │   └── amdefine@1.0.1 
│ ├── esprima@2.7.3 
│ ├── glob@5.0.15 
│ ���─┬ handlebars@4.1.0 
│ │ ├── async@2.6.2 
│ │ ├─┬ optimist@0.6.1 
│ │ │ ├── minimist@0.0.10 
│ │ │ └── wordwrap@0.0.3 
│ │ ├── source-map@0.6.1 
│ │ └─┬ uglify-js@3.4.9 
│ │   ├── commander@2.17.1 
│ │   └── source-map@0.6.1 
│ ├─┬ once@1.4.0 
│ │ └── wrappy@1.0.2 
│ ├── resolve@1.1.7 
│ ├─┬ supports-color@3.2.3 
│ │ └── has-flag@1.0.0 
│ ├─┬ which@1.3.1 
│ │ └── isexe@2.0.0 
│ └── wordwrap@1.0.0 
├─┬ jshint@2.10.1 
│ ├─┬ cli@1.0.1 
│ │ └── glob@7.1.3 
│ ├─┬ console-browserify@1.1.0 
│ │ └── date-now@0.1.4 
│ ├─┬ htmlparser2@3.8.3 
│ │ ├── domelementtype@1.3.1 
│ │ ├── domhandler@2.3.0 
│ │ ├─┬ domutils@1.5.1 
│ │ │ └─┬ dom-serializer@0.1.1 
│ │ │   └── entities@1.1.2 
│ │ ├── entities@1.0.0 
│ │ └─┬ readable-stream@1.1.14 
│ ���   ├── core-util-is@1.0.2 
│ │   ├── isarray@0.0.1 
│ │   └── string_decoder@0.10.31 
│ ├── shelljs@0.3.0 
│ └── strip-json-comments@1.0.4 
├── lodash.camelcase@4.3.0 
├── lodash.endswith@4.2.1 
├── lodash.find@4.6.0 
├── lodash.maxby@4.6.0 
├── lodash.padend@4.6.1 
├── lodash.startswith@4.2.1 
├─┬ mocha@6.0.2 
│ ├── ansi-colors@3.2.3 
│ ├── browser-stdout@1.3.1 
│ ├── debug@3.2.6 
│ ├── diff@3.5.0 
│ ├── escape-string-regexp@1.0.5 
│ ├─┬ findup-sync@2.0.0 
│ │ ├── detect-file@1.0.0 
│ │ ├─┬ is-glob@3.1.0 
│ │ │ └── is-extglob@2.1.1 
│ │ ├─┬ micromatch@3.1.10 
│ │ │ ├── arr-diff@4.0.0 
│ │ │ ├── array-unique@0.3.2 
│ │ │ ├─┬ braces@2.3.2 
│ │ │ │ ├── arr-flatten@1.1.0 
│ │ │ │ ├─┬ extend-shallow@2.0.1 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ fill-range@4.0.0 
│ │ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ │ ├─┬ is-number@3.0.0 
│ │ │ │ │ │ └─┬ kind-of@3.2.2 
│ │ │ │ │ │   └── is-buffer@1.1.6 
│ │ │ │ │ ├── repeat-string@1.6.1 
│ │ │ │ │ └── to-regex-range@2.1.1 
│ │ │ │ ├── repeat-element@1.1.3 
│ │ │ │ ├─┬ snapdragon-node@2.1.1 
│ │ │ │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ │ └─┬ snapdragon-util@3.0.1 
│ │ │ │ │   └── kind-of@3.2.2 
│ │ │ │ └── split-string@3.1.0 
│ │ │ ├─┬ define-property@2.0.2 
│ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ ├─┬ extend-shallow@3.0.2 
│ │ │ │ ├── assign-symbols@1.0.0 
│ │ │ │ └── is-extendable@1.0.1 
│ │ │ ├─┬ extglob@2.0.4 
│ ��� │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ ├─┬ expand-brackets@2.1.4 
│ │ │ │ │ ├── define-property@0.2.5 
│ │ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ │ └── posix-character-classes@0.1.1 
│ │ │ │ └── extend-shallow@2.0.1 
│ │ │ ├── fragment-cache@0.2.1 
│ │ │ ├── kind-of@6.0.2 
│ │ │ ├─┬ nanomatch@1.2.13 
│ │ │ │ └── is-windows@1.0.2 
│ │ │ ├─┬ regex-not@1.0.2 
│ │ │ │ └─┬ safe-regex@1.1.0 
│ │ │ │   └── ret@0.1.15 
│ │ │ ├─┬ snapdragon@0.8.2 
│ │ │ │ ├─┬ base@0.11.2 
│ │ │ │ │ ├─┬ cache-base@1.0.1 
│ │ │ │ │ │ ├─┬ collection-visit@1.0.0 
│ │ │ │ │ │ │ ├── map-visit@1.0.0 
│ │ │ │ │ │ │ └── object-visit@1.0.1 
│ │ │ │ │ │ ├── get-value@2.0.6 
│ │ │ │ │ │ ├─┬ has-value@1.0.0 
│ │ │ │ │ │ │ └─┬ has-values@1.0.0 
│ │ │ │ │ │ │   └── kind-of@4.0.0 
│ │ │ │ │ │ ├─┬ set-value@2.0.0 
│ │ │ │ │ │ │ └── extend-shallow@2.0.1 
│ │ │ │ │ │ ├─┬ to-object-path@0.3.0 
│ │ │ │ │ │ │ └── kind-of@3.2.2 
│ │ │ │ │ │ ├─┬ union-value@1.0.0 
│ │ │ │ │ │ │ └─┬ set-value@0.4.3 
│ │ │ │ │ │ │   └── extend-shallow@2.0.1 
│ │ │ │ │ │ └─┬ unset-value@1.0.0 
│ │ │ │ │ │   └─┬ has-value@0.3.1 
│ │ │ │ │ │     ├── has-values@0.1.4 
│ │ │ │ │ │     └── isobject@2.1.0 
│ │ │ │ │ ├─┬ class-utils@0.3.6 
│ │ │ │ │ │ ├── arr-union@3.1.0 
│ │ │ │ │ │ ├── define-property@0.2.5 
│ │ │ │ │ │ └─┬ static-extend@0.1.2 
│ │ │ │ │ │   ├── define-property@0.2.5 
│ │ │ │ │ │   └─┬ object-copy@0.1.0 
│ │ │ │ │ │     ├── copy-descriptor@0.1.1 
│ │ │ │ │ │     ├── define-property@0.2.5 
│ │ │ │ │ │     ���── kind-of@3.2.2 
│ │ │ │ │ ├── component-emitter@1.2.1 
│ │ │ │ │ ├─┬ define-property@1.0.0 
│ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
│ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
│ │ │ │ │ │   └── is-data-descriptor@1.0.0 
│ │ │ │ │ ├─┬ mixin-deep@1.3.1 
│ │ │ │ │ │ └── is-extendable@1.0.1 
│ │ │ │ │ └── pascalcase@0.1.1 
│ │ │ │ ├─┬ debug@2.6.9 
│ │ │ │ │ └── ms@2.0.0 
│ │ │ │ ├─┬ define-property@0.2.5 
│ │ │ │ │ └─┬ is-descriptor@0.1.6 
│ │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6 
│ │ │ │ │   │ └── kind-of@3.2.2 
│ │ │ │ │   ├─┬ is-data-descriptor@0.1.4 
│ │ │ │ │   │ └── kind-of@3.2.2 
│ │ │ │ │   └── kind-of@5.1.0 
│ │ │ │ ├── extend-shallow@2.0.1 
│ │ │ │ ├─┬ source-map-resolve@0.5.2 
│ │ │ │ │ ├── atob@2.1.2 
│ │ │ │ │ ├── decode-uri-component@0.2.0 
│ │ │ │ │ ├── resolve-url@0.2.1 
│ │ │ │ │ ├── source-map-url@0.4.0 
│ │ │ │ │ └── urix@0.1.0 
│ │ │ │ └── use@3.1.1 
│ │ │ └── to-regex@3.0.2 
│ │ └─┬ resolve-dir@1.0.1 
│ │   └─┬ global-modules@1.0.0 
│ │     └── global-prefix@1.0.2 
│ ├── glob@7.1.3 
│ ├── he@1.2.0 
│ ├── js-yaml@3.12.0 
│ ├── log-symbols@2.2.0 
│ ├── ms@2.1.1 
│ ├─┬ node-environment-flags@1.0.4 
│ │ └─┬ object.getownpropertydescriptors@2.0.3 
│ │   └─┬ es-abstract@1.13.0 
│ │     ├─┬ es-to-primitive@1.2.0 
│ │     │ ├── is-date-object@1.0.1 
│ │     │ └── is-symbol@1.0.2 
│ │     ├── has@1.0.3 
│ │     ├── is-callable@1.1.4 
│ │     └── is-regex@1.0.4 
│ ├─┬ object.assign@4.1.0 
│ │ ├── define-properties@1.1.3 
│ │ ├── function-bind@1.1.1 
│ │ ├── has-symbols@1.0.0 
│ │ └── object-keys@1.1.0 
│ ├── strip-json-comments@2.0.1 
│ ├─┬ supports-color@6.0.0 
│ │ └── has-flag@3.0.0 
│ ├─┬ wide-align@1.1.3 
│ │ └─┬ string-width@2.1.1 
│ │   ├── is-fullwidth-code-point@2.0.0 
│ │   └─┬ strip-ansi@4.0.0 
│ │     └── ansi-regex@3.0.0 
│ ├─┬ yargs@12.0.5 
│ │ ├─┬ cliui@4.1.0 
│ │ │ ├─┬ strip-ansi@4.0.0 
│ │ │ │ └── ansi-regex@3.0.0 
│ │ │ └─┬ wrap-ansi@2.1.0 
│ │ │   └─┬ string-width@1.0.2 
│ │ │     ├── code-point-at@1.1.0 
│ │ │     └─┬ is-fullwidth-code-point@1.0.0 
│ │ │       └── number-is-nan@1.0.1 
│ │ ├── decamelize@1.2.0 
│ │ ├─┬ find-up@3.0.0 
│ │ │ └─┬ locate-path@3.0.0 
│ │ │   ├─┬ p-locate@3.0.0 
│ │ │   │ └─┬ p-limit@2.2.0 
│ │ │   │   └── p-try@2.0.0 
│ │ │   └── path-exists@3.0.0 
│ │ ├── get-caller-file@1.0.3 
│ │ ├─┬ os-locale@3.1.0 
│ │ │ ├─┬ execa@1.0.0 
│ │ │ │ ├─┬ cross-spawn@6.0.5 
│ │ │ │ │ ├── nice-try@1.0.5 
│ │ │ │ │ ├── path-key@2.0.1 
│ │ │ │ │ └─┬ shebang-command@1.2.0 
│ │ │ │ │   └── shebang-regex@1.0.0 
│ │ │ │ ├─┬ get-stream@4.1.0 
│ │ │ │ │ └─┬ pump@3.0.0 
│ │ │ │ │   └── end-of-stream@1.4.1 
│ │ │ │ ├── is-stream@1.1.0 
│ │ │ │ ├── npm-run-path@2.0.2 
│ │ │ │ ├── p-finally@1.0.0 
│ │ │ │ └── strip-eof@1.0.0 
│ │ │ ├─┬ lcid@2.0.0 
│ │ │ │ └── invert-kv@2.0.0 
│ │ │ └─┬ mem@4.1.0 
│ │ │   ├─┬ map-age-cleaner@0.1.3 
│ │ │   │ └── p-defer@1.0.0 
│ │ │   ├── mimic-fn@1.2.0 
│ │ │   └── p-is-promise@2.0.0 
│ │ ├── require-directory@2.1.1 
│ │ ├── require-main-filename@1.0.1 
│ │ ├── set-blocking@2.0.0 
│ │ ├── which-module@2.0.0 
│ │ └── y18n@4.0.0 
│ ├─┬ yargs-parser@11.1.1 
│ │ └── camelcase@5.2.0 
│ └─┬ yargs-unparser@1.5.0 
│   └─┬ flat@4.1.0 
│     └── is-buffer@2.0.3 
└── mocha-lcov-reporter@1.3.0 
1.94s$ npm run test-sa
> snack-cli@1.1.0 test-sa /home/travis/build/subchen/snack-cli
> grunt sa
Running "trimtrailingspaces:main" (trimtrailingspaces) task
>> 12 files free of trailing whitespace.
Running "jsbeautifier:files" (jsbeautifier) task
Beautified 12 files, changed 0 files...OK
Running "jshint:files" (jshint) task
>> 12 files lint free.
Running "jscs:files" (jscs) task
Warning: Config values to remove in 3.0:
The `esnext` option is enabled by default. Use --force to continue.
Aborted due to warnings.
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.17.0/bin/node" "/home/travis/.nvm/versions/node/v6.17.0/bin/npm" "run" "test-sa"
npm ERR! node v6.17.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! snack-cli@1.1.0 test-sa: `grunt sa`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the snack-cli@1.1.0 test-sa script 'grunt sa'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snack-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt sa
npm ERR!m You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snack-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snack-cli
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/subchen/snack-cli/npm-debug.log
The command "npm run test-sa" exited with 1.
1.37s$ npm run test-cc
> snack-cli@1.1.0 test-cc /home/travis/build/subchen/snack-cli
> istanbul cover _mocha -- --reporter mocha-lcov-reporter
mocha-lcov-reporter: No coverage data found, make sure your code is properly instrumented
=============================================================================
Writing coverage object [/home/travis/build/subchen/snack-cli/coverage/coverage.json]
Writing coverage reports at [/home/travis/build/subchen/snack-cli/coverage]
=============================================================================
=============================== Coverage summary ===============================
Statements   : 94.25% ( 213/226 )
Branches     : 89.02% ( 73/82 )
Functions    : 87.8% ( 36/41 )
Lines        : 94.25% ( 213/226 )
================================================================================
The command "npm run test-cc" exited with 0.
after_script
1.70s$ npm run test-cc-post
> snack-cli@1.1.0 test-cc-post /home/travis/build/subchen/snack-cli
> cat ./coverage/lcov.info | coveralls
Done. Your build exited with 1.
```

**Comment by williamdes** [comment]
@subchen Only latest node version failed, 99% fixed now :)

**Comment by williamdes** [comment]
@subchen I fixed all the errors, you can review and merge if you want ;)

**Comment by subchen** [comment]
thanks again, that's all passed

**Pull request merged**
